# Generated by Django 2.2.9 on 2019-12-31 08:23

import codehub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.CharField(default=codehub.models.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=10)),
                ('code', models.TextField(default='')),
                ('paste_time', models.DateTimeField(auto_now=True)),
                ('password', models.TextField(default=None, null=True)),
            ],
        ),
    ]
