# Generated by Django 2.2.6 on 2019-11-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('language', models.CharField(choices=[('plaintext', 'plaintext'), ('Apache', 'Apache'), ('Bash', 'Bash'), ('C#', 'C#'), ('C++', 'C++'), ('CSS', 'CSS'), ('CoffeeScript', 'CoffeeScript'), ('Diff', 'Diff'), ('HTML', 'HTML'), ('XML', 'XML'), ('HTTP', 'HTTP'), ('Ini', 'Ini'), ('TOML', 'TOML'), ('JSON', 'JSON'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('Makefile', 'Makefile'), ('Markdown', 'Markdown'), ('Nginx', 'Nginx'), ('Objective-C', 'Objective-C'), ('PHP', 'PHP'), ('Perl', 'Perl'), ('Properties', 'Properties'), ('Python', 'Python'), ('Ruby', 'Ruby'), ('SQL', 'SQL'), ('Shell', 'Shell'), ('Session', 'Session')], default=1, max_length=10)),
                ('code', models.TextField(default='')),
                ('paste_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
