# Generated by Django 2.2.6 on 2019-11-11 05:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0002_auto_20191110_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
