# Generated by Django 2.2.6 on 2019-11-11 05:56

from django.db import migrations, models
import robot.models.CodeHub.Code


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_auto_20191111_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='id',
            field=models.UUIDField(default=robot.models.CodeHub.Code.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
    ]
