# Generated by Django 2.2.6 on 2019-11-11 06:03

from django.db import migrations, models
import robot.models.CodeHub.Code


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0005_auto_20191111_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='id',
            field=models.CharField(default=robot.models.CodeHub.Code.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
