# Generated by Django 2.2.6 on 2019-11-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0006_auto_20191111_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='password',
            field=models.TextField(default=None, null=True),
        ),
    ]
