# Generated by Django 2.2.6 on 2019-12-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0009_article_user_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
