# Generated by Django 2.2.9 on 2019-12-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32)),
                ('term', models.IntegerField()),
                ('data', models.TextField(default='')),
                ('last_modify_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
